{
 "title": "U-BMC All Hosts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Board Temperatures",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_temperature_reading_celsius{physical_context=\"Systemboard\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Midplane Temperatures",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_temperature_reading_celsius{physical_context=\"midplane\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "PSU Temperatures",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_temperature_reading_celsius{physical_context=~\"PSU backplane|psu1|psu2|psu3|psu4\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "options": { "content": " " },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fan Speed",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 1, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_fan_speed_reading_rpm{}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Voltage Sensors",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_voltage_reading_volts{}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}