{
 "title": "U-BMC By Hostname",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(redfish_fan_speed_reading_rpm, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperatures",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_temperature_reading_celsius{id=~\"midplane-gpu1_temp|midplane-gpu2_temp|midplane-gpu3_temp|midplane-gpu4_temp\",host=\"${Hostname}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_fan_speed_reading_rpm{host=\"${Hostname}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "GPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "redfish_temperature_reading_celsius{id=~\"midplane-gpu1_temp|midplane-gpu2_temp|midplane-gpu3_temp|midplane-gpu4_temp\",host=\"${Hostname}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Power Supply Output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "redfish_power_supply_last_power_output_watts{host=\"${Hostname}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Voltage Sensor Readings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_voltage_reading_volts{host=\"${Hostname}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}